[build.environment]
NODE_VERSION = "20"
NODE_MODULES_CACHE = "false"

[[redirects]]
from = "/readme"
to = "/index.html"
status = 200

[[redirects]]
from = "/iam"
to = "/index.html"
status = 200

[[redirects]]
from = "/iam-usecase"
to = "/index.html"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
