// O*NET Standardized Transferable Skills Position Map (S01–S35)
// See: specs/personality-specs/personality_code.spec.md

export const skillPositionMap = [
  { index: 'S01', name: 'Reading Comprehension', category: 'Cognitive & Analysis' },
  { index: 'S02', name: 'Active Listening', category: 'Communication & Interpersonal' },
  { index: 'S03', name: 'Writing', category: 'Communication & Interpersonal' },
  { index: 'S04', name: 'Speaking', category: 'Communication & Interpersonal' },
  { index: 'S05', name: 'Mathematics', category: 'Cognitive & Analysis' },
  { index: 'S06', name: 'Science', category: 'Cognitive & Analysis' },
  { index: 'S07', name: 'Critical Thinking', category: 'Cognitive & Analysis' },
  { index: 'S08', name: 'Active Learning', category: 'Cognitive & Analysis' },
  { index: 'S09', name: 'Learning Strategies', category: 'Cognitive & Analysis' },
  { index: 'S10', name: 'Monitoring', category: 'Cognitive & Analysis' },
  { index: 'S11', name: 'Social Perceptiveness', category: 'Communication & Interpersonal' },
  { index: 'S12', name: 'Coordination', category: 'Communication & Interpersonal' },
  { index: 'S13', name: 'Persuasion', category: 'Communication & Interpersonal' },
  { index: 'S14', name: 'Negotiation', category: 'Communication & Interpersonal' },
  { index: 'S15', name: 'Instructing', category: 'Communication & Interpersonal' },
  { index: 'S16', name: 'Service Orientation', category: 'Communication & Interpersonal' },
  { index: 'S17', name: 'Complex Problem Solving', category: 'Cognitive & Analysis' },
  { index: 'S18', name: 'Troubleshooting', category: 'Technical & Specialized' },
  { index: 'S19', name: 'Operations Analysis', category: 'Business & Process' },
  { index: 'S20', name: 'Technology Design', category: 'Technical & Specialized' },
  { index: 'S21', name: 'Equipment Selection', category: 'Business & Process' },
  { index: 'S22', name: 'Installation', category: 'Technical & Specialized' },
  { index: 'S23', name: 'Programming', category: 'Technical & Specialized' },
  { index: 'S24', name: 'Quality Control Analysis', category: 'Technical & Specialized' },
  { index: 'S25', name: 'Equipment Maintenance', category: 'Technical & Specialized' },
  { index: 'S26', name: 'Repairing', category: 'Technical & Specialized' },
  { index: 'S27', name: 'Time Management', category: 'Business & Process' },
  { index: 'S28', name: 'Management of Financial Resources', category: 'Business & Process' },
  { index: 'S29', name: 'Management of Material Resources', category: 'Business & Process' },
  { index: 'S30', name: 'Management of Personnel Resources', category: 'Leadership & Management' },
  { index: 'S31', name: 'Identify Patterns', category: 'Cognitive & Analysis' },
  { index: 'S32', name: 'Data Analysis', category: 'Cognitive & Analysis' },
  { index: 'S33', name: 'Systems Evaluation', category: 'Cognitive & Analysis' },
  { index: 'S34', name: 'Judgment & Decision Making', category: 'Cognitive & Analysis' },
  { index: 'S35', name: 'Creativity & Innovation', category: 'Creative & Innovation' }
];
